
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" # machine:container

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # machine:container
    depends_on:
      - backend # frontend starts after backend
